### ISSUE TITLE
LDAP URL with multiple attributes throws exception

### ISSUE THREAD

**Issue by akkornel** [akkornel/syncrepl#17]
If an LDAP URL is used which requests multiple attributes, an exception will be thrown.

For example, the following command will throw: `syncrepl-client --persist  ldaps://directory-master.stanford.edu:636/cn=people,dc=stanford,dc=edu?suSunetID,suPrivilegeGroup?sub?uid=ljlgeek?bindname=GSSAPI karl`

The output which appears is:

```
Data files will be stored here: karl
Refresh-and-persist mode will be used
CLIENT SETUP START
Traceback (most recent call last):
  File "/Users/akkornel/Library/Python/3.6/bin/syncrepl-client", line 92, in <module>
    else SyncreplMode.REFRESH_ONLY
  File "/Users/akkornel/Library/Python/3.6/lib/python/site-packages/syncrepl_client/__init__.py", line 397, in __init__
    SimpleLDAPObject.__init__(self, ldap_url.unparse(), **kwargs)
  File "/Users/akkornel/Library/Python/3.6/lib/python/site-packages/pyldap-2.4.37-py3.6-macosx-10.12-x86_64.egg/ldap/ldapobject.py", line 87, in __init__
    self._l = ldap.functions._ldap_function_call(ldap._ldap_module_lock,_ldap.initialize,uri)
  File "/Users/akkornel/Library/Python/3.6/lib/python/site-packages/pyldap-2.4.37-py3.6-macosx-10.12-x86_64.egg/ldap/functions.py", line 66, in _ldap_function_call
    result = func(*args,**kwargs)
ldap.LDAPError: (2, 'No such file or directory')
Exception ignored in: <bound method Syncrepl.__del__ of <syncrepl_client.Syncrepl object at 0x108f873c8>>
Traceback (most recent call last):
  File "/Users/akkornel/Library/Python/3.6/lib/python/site-packages/syncrepl_client/__init__.py", line 502, in __del__
    return self.unbind()
  File "/Users/akkornel/Library/Python/3.6/lib/python/site-packages/syncrepl_client/__init__.py", line 480, in unbind
    unbind_result = SimpleLDAPObject.unbind(self)
  File "/Users/akkornel/Library/Python/3.6/lib/python/site-packages/pyldap-2.4.37-py3.6-macosx-10.12-x86_64.egg/ldap/ldapobject.py", line 852, in unbind
    return self.unbind_ext(None,None)
  File "/Users/akkornel/Library/Python/3.6/lib/python/site-packages/pyldap-2.4.37-py3.6-macosx-10.12-x86_64.egg/ldap/ldapobject.py", line 831, in unbind_ext
    res = self._ldap_call(self._l.unbind_ext,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
  File "/Users/akkornel/Library/Python/3.6/lib/python/site-packages/pyldap-2.4.37-py3.6-macosx-10.12-x86_64.egg/ldap/ldapobject.py", line 329, in __getattr__
    self.__class__.__name__,repr(name)
AttributeError: Syncrepl has no attribute '_l'
```

**Comment by akkornel** [comment]
Things to note:

• From https://linux.die.net/man/3/ldap_initialize

> ldap_initialize() …. The uri parameter may be a comma- or whitespace-separated list of URIs containing only the schema, the host, and the port fields. …

• From https://www.python-ldap.org/doc/html/ldap.html#ldap.initialize:

> Parameter uri has to be a valid LDAP URL.

**Comment by akkornel** [comment]
This also affects pyldap, but needs to be reported upstream to python-ldap.  In the mean time, I should change my code to strip the LDAP URL before I hand it up to python-ldap.
