### ISSUE TITLE
The shelve goes BOOM

### ISSUE THREAD

**Issue by akkornel** [akkornel/syncrepl#19]
379,239 partial records.  The BDB file was about 550 MB on-disk.

```
DN0a626bf0:~/git/wglurp akkornel(p)$ ~/Library/Python/3.6/bin/wglurp-ldap -f
Added program-startup handler.  Log to stderr until early-start is complete.
Disabling log propagation.
[61362] [logging.py:42 (<module>)] INFO: stanford_wglurp (wglurp-ldap) version 0.0.1 early startup...
[61362] [logging.py:75 (<module>)] DEBUG: Installing custom last-resort exception-handler hook.
[61362] [config.py:76 (<module>)] DEBUG: Setting configuration defaults.
[61362] [config.py:113 (<module>)] DEBUG: Reading configuration files...
[61362] [config.py:59 (find_config_files)] DEBUG: Will load config files in the following order: ['/opt/local/Library/Frameworks/Python.framework/Versions/3.6/etc/wglurp.conf', '/Users/akkornel/.wglurp.conf']
[61362] [config.py:145 (<module>)] DEBUG: Valdating read configuration...
[61362] [logging.py:105 (<module>)] DEBUG: Configured log target is /Users/akkornel/git/wglurp/log
[61362] [logging.py:201 (<module>)] INFO: Will log to file at path /Users/akkornel/git/wglurp/log.
[61362] [logging.py:212 (<module>)] INFO: Running in foreground.  Logs will now go to stdout.  (The next entry will log to both stdout and stderr.)
[61362] [logging.py:221 (<module>)] INFO: Program-startup logging to stderr will now end.
[61362] [logging.py:221 (<module>)] INFO: Program-startup logging to stderr will now end.
[61362] [logging.py:229 (<module>)] INFO: Welcome to stanford_wglurp (wglurp-ldap) version 0.0.1!
[61362] [logging.py:234 (<module>)] INFO: Logging threshold changed to INFO
[61362] [ldap.py:354 (main)] INFO: Metrics will write to "/Users/akkornel/git/wglurp/metrics/ldap"
[61362] [ldap.py:370 (main)] INFO: LDAP URL is ldaps://ldap-master.stanford.edu:636/cn%3Dpeople%2Cdc%3Dstanford%2Cdc%3Dedu?suRegID,uid,suPrivilegeGroup?sub?%28objectClass%3D%2A%29?bindname=GSSAPI
[61362] [ldap.py:55 (bind_complete)] INFO: LDAP bind complete!  We are "dn:uid=akkornel,cn=accounts,dc=stanford,dc=edu"
[61362] [ldap.py:426 (main)] INFO: LDAP client thread #123145468792832 launched!
[61362] [ldap.py:438 (main)] INFO: LDAP metrics thread #123145474048000 launched!
HASH: Out of overflow pages.  Increase page size
Exception in thread LDAP client:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/akkornel/Library/Python/3.6/lib/python/site-packages/syncrepl_client-0.95.1-py3.6.egg/syncrepl_client/__init__.py", line 696, in run
    poll_result = self.poll()
  File "/Users/akkornel/Library/Python/3.6/lib/python/site-packages/syncrepl_client-0.95.1-py3.6.egg/syncrepl_client/__init__.py", line 604, in poll
    all=1, timeout=3)
  File "/Users/akkornel/Library/Python/3.6/lib/python/site-packages/ldap/syncrepl.py", line 385, in syncrepl_poll
    self.syncrepl_entry(dn, attrs, c.entryUUID)
  File "/Users/akkornel/Library/Python/3.6/lib/python/site-packages/syncrepl_client-0.95.1-py3.6.egg/syncrepl_client/__init__.py", line 1099, in syncrepl_entry
    self.__uuid_attrs[uuid] = attrs
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shelve.py", line 125, in __setitem__
    self.dict[key.encode(self.keyencoding)] = f.getvalue()
_dbm.error: cannot add item to database

HASH: Out of overflow pages.  Increase page size
[61362] [logging.py:63 (handle_exception)] CRITICAL: UNCAUGHT EXCEPTION!
[61362] [logging.py:69 (handle_exception)] CRITICAL: _dbm.error: cannot add item to database
[61362] [logging.py:69 (handle_exception)] CRITICAL: TRACEBACK (failing call last):
[61362] [logging.py:69 (handle_exception)] CRITICAL:   File "/Users/akkornel/Library/Python/3.6/bin/wglurp-ldap", line 11, in <module>
[61362] [logging.py:69 (handle_exception)] CRITICAL:     load_entry_point('stanford-wglurp', 'console_scripts', 'wglurp-ldap')()
[61362] [logging.py:69 (handle_exception)] CRITICAL:   File "/Users/akkornel/git/wglurp/stanford_wglurp/ldap.py", line 463, in main
[61362] [logging.py:69 (handle_exception)] CRITICAL:     client.unbind()
[61362] [logging.py:69 (handle_exception)] CRITICAL:   File "/Users/akkornel/Library/Python/3.6/lib/python/site-packages/syncrepl_client-0.95.1-py3.6.egg/syncrepl_client/__init__.py", line 497, in unbind
[61362] [logging.py:69 (handle_exception)] CRITICAL:     self.__uuid_attrs.close()
[61362] [logging.py:69 (handle_exception)] CRITICAL:   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shelve.py", line 144, in close
[61362] [logging.py:69 (handle_exception)] CRITICAL:     self.sync()
[61362] [logging.py:69 (handle_exception)] CRITICAL:   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shelve.py", line 168, in sync
[61362] [logging.py:69 (handle_exception)] CRITICAL:     self[key] = entry
[61362] [logging.py:69 (handle_exception)] CRITICAL:   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shelve.py", line 125, in __setitem__
[61362] [logging.py:69 (handle_exception)] CRITICAL:     self.dict[key.encode(self.keyencoding)] = f.getvalue()
```

**Comment by akkornel** [comment]
I guess time to change from shelve to sqlite3.

**Comment by akkornel** [comment]
(Correction, it was a dbm file, not a bdb file.)

**Comment by akkornel** [comment]
This has been fixed by a series of commits, the last one of the series being a229a24.
