### ISSUE TITLE
pyldap 3.0 incompatibility

### ISSUE THREAD

**Issue by landryb** [akkornel/syncrepl#34]
If pyldap 3.0.0post1 is installed instead of 2.4.37, refresh-and-persist will bail out at the end of the initial syncwith the following traceback:
```
Exception in thread ldapwatch:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/data/web/nextcloud/venv/lib/python3.5/site-packages/syncrepl_client/__init__.py", line 801, in run
    poll_result = self.poll()
  File "/data/web/nextcloud/venv/lib/python3.5/site-packages/syncrepl_client/__init__.py", line 702, in poll
    all=1, timeout=3)
  File "/data/web/nextcloud/venv/lib/python3.5/site-packages/ldap/syncrepl.py", line 448, in syncrepl_poll
    sim = SyncInfoMessage(resp)
  File "/data/web/nextcloud/venv/lib/python3.5/site-packages/ldap/syncrepl.py", line 320, in __init__
    if comp is not None and comp.hasValue():
AttributeError: 'RefreshDelete' object has no attribute 'hasValue'

```

**Comment by landryb** [comment]
it *seems* python-ldap/python-ldap#351 fixed this issue, `syncrepl-client --persist` test client doesnt crash after the initial sync, and subsequent changes are properly handled. So *maybe* requiring python-ldap 3.3.0 instead of pyldap 2.4.37 would be enough...
